{
 "title": "Kafka Producer",
 "description": "Java client Kafka Producer metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "Client ID",
    "query": {
     "query": "label_values(kafka_app_info_start_time_ms, client_id)"
    }
   },
   {
    "name": "topic",
    "label": "Kafka topic",
    "query": {
     "query": "label_values(kafka_producer_record_send_total, topic)"
    }
   },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_app_info_start_time_ms, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Disclaimer\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   }
  },
  {
   "title": "Retry rate",
   "type": "stat",
   "description": "The average per-second number of retried record sends for a topic. An increase could signal connectivity problems from the application to the broker. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_rate{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "stat",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_error_total{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Free buffer space",
   "type": "stat",
   "description": "he total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "stat",
   "description": "The average compression rate of record batches for a topic, defined as the average ratio of the compressed batch size over the uncompressed size.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "timeseries",
   "description": "The average request latency in ms.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Record queue time",
   "type": "timeseries",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Failed authentication rate",
   "type": "timeseries",
   "description": "The rate of failed authentication per seconds\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_failed_authentication_total{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "{{job}}@{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{instance=~\"$instance\"})",
       "legendFormat": "{{job}}@{{instance}}"
      },
      {
       "expr": "jvm_memory_bytes_max{job=\"kafka-connect\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\",area=\"heap\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM GC time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{job}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing byte rate",
     "type": "timeseries",
     "description": "The average number of bytes sent per second to the broker.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_outgoing_byte_total{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing byte rate per topic",
     "type": "timeseries",
     "description": "The average number of bytes sent per second to the broker per topic.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_byte_total{client_id=~\"$client_id\",instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Outgoing messages per second",
     "type": "timeseries",
     "description": "The average number of messages sent per second to the broker.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_record_send_total{client_id=~\"$client_id\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing messages per second per topic",
     "type": "timeseries",
     "description": "The average number of messages sent per second to the broker per topic.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_record_send_total{client_id=~\"$client_id\", instance=~\"$instance\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch size average",
     "type": "timeseries",
     "description": "The average number of bytes sent per partition per-request.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_batch_size_avg{client_id=~\"$client_id\", instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Request in flight",
     "type": "timeseries",
     "description": "The current number of in-flight requests awaiting a response.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_requests_in_flight{client_id=~\"$client_id\", instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Record size average",
     "type": "timeseries",
     "description": "The average record size",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kafka_producer_record_size_avg{client_id=~\"$client_id\", instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Produce Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce request rate",
     "type": "timeseries",
     "description": "The average number of requests sent per second to the broker.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_request_total{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Produce request size average",
     "type": "timeseries",
     "description": "The average number of records per request.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "kafka_producer_request_size_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Produce response rate",
     "type": "timeseries",
     "description": "The average number of response received per second to the broker.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_response_total{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection rate",
     "type": "timeseries",
     "description": "The current number of active connections.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_connection_count{client_id=~\"$client_id\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Connection creation rate",
     "type": "timeseries",
     "description": "New connections established per second in the window.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_connection_creation_rate{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Connection close rate",
     "type": "timeseries",
     "description": "Connections closed per second in the window.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_connection_close_rate{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "timeseries",
     "description": "The fraction of time the I/O thread spent doing I/O.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_io_ratio{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "IO Wait time average",
     "type": "timeseries",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_producer_io_wait_time_ns_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "IO Time average",
     "type": "timeseries",
     "description": "The average length of time for I/O per select call in nanoseconds.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_producer_io_time_ns_avg{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "IO Wait Ratio",
     "type": "timeseries",
     "description": "The fraction of time the I/O thread spent waiting.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_io_wait_ratio{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Select Rate",
     "type": "timeseries",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_select_rate{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Version",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_app_info_start_time_ms{client_id=~\"$client_id\",instance=~\"$instance\",version!=\"\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Metadata max age",
     "type": "timeseries",
     "description": "The age in seconds of the current producer metadata being used.",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_metadata_age{client_id=~\"$client_id\",instance=~\"$instance\"}",
       "legendFormat": "{{client_id}}@{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}