services:
  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./assets/prometheus/prometheus-config/:/etc/prometheus

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./assets/grafana/provisioning/:/etc/grafana/provisioning

  tryg-demo:
    container_name: tryg-demo-app
    image: amykoh/tryg-demo-app
    ports:
      - "9000:9000"